name: Build Pipeline

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - 'experimental'

env:
  # environment variables to config `turbo` to use the local cache server
  TURBO_API: 'http://127.0.0.1:9080'
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: 'dinero'
  TURBO_REMOTE_ONLY: true
  # Used by scripts/build-types.mjs
  CI: true

permissions:
  checks: write
  contents: read
  statuses: write
  pull-requests: read

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Environment
        uses: ./.github/actions/turbo
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Test types
        run: yarn test:types

      - name: Test bundle size
        run: yarn test:size
